/* Generated By:JavaCC: Do not edit this line. InvariantParserTreeConstants.java Version 5.0 */
package invariant.invariantEvaluator.Parser;

public interface InvariantParserTreeConstants
{
  public int JJTINV_EXP = 0;
  public int JJTOREXPR = 1;
  public int JJTANDEXPR = 2;
  public int JJTATOMINV = 3;
  public int JJTRANGE = 4;
  public int JJTSET = 5;
  public int JJTARITM = 6;
  public int JJTSUMEXPR = 7;
  public int JJTMULTEXPR = 8;
  public int JJTATOM = 9;


  public String[] jjtNodeName = {
    "Inv_exp",
    "OrExpr",
    "AndExpr",
    "atomInv",
    "Range",
    "Set",
    "Aritm",
    "SumExpr",
    "multExpr",
    "atom",
  };
}
/* JavaCC - OriginalChecksum=e9ffe419e8b603f13f436a97e9186b0c (do not edit this line) */
