/* Generated By:JavaCC: Do not edit this line. InvariantParserTreeConstants.java Version 5.0 */
package invariant.invariantEvaluator.Parser;

public interface InvariantParserTreeConstants
{
  public int JJTINV_EXP = 0;
  public int JJTOREXPR = 1;
  public int JJTANDEXPR = 2;
  public int JJTATOMINV = 3;
  public int JJTRANGE = 4;
  public int JJTSET = 5;
  public int JJTVARDECL = 6;
  public int JJTARITM = 7;
  public int JJTSUMEXPR = 8;
  public int JJTMULTEXPR = 9;
  public int JJTATOM = 10;


  public String[] jjtNodeName = {
    "Inv_exp",
    "OrExpr",
    "AndExpr",
    "atomInv",
    "Range",
    "Set",
    "VarDecl",
    "Aritm",
    "SumExpr",
    "multExpr",
    "atom",
  };
}
/* JavaCC - OriginalChecksum=450402bc6bd3ccb0e943d4c8b9fbc876 (do not edit this line) */
