/* Generated By:JJTree&JavaCC: Do not edit this line. InvariantParserConstants.java */
/*Coisas p/ adicionar depois de compilar:
 SimpleNode:

  public Vector<Integer> operators;
  public String numVar;
  public boolean negative;
  public int getID() throws ParseException{
	return id;
  }
  

*/

package invariant.invariantEvaluator.Parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InvariantParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 4;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int REC_BRAC_O = 8;
  /** RegularExpression Id. */
  int REC_BRAC_C = 9;
  /** RegularExpression Id. */
  int PAR_OPEN = 10;
  /** RegularExpression Id. */
  int PAR_CLOSE = 11;
  /** RegularExpression Id. */
  int PAR_SETO = 12;
  /** RegularExpression Id. */
  int PAR_SETC = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int NOTEQUAL = 16;
  /** RegularExpression Id. */
  int INF = 17;
  /** RegularExpression Id. */
  int OP_SUM = 18;
  /** RegularExpression Id. */
  int OP_DIFF = 19;
  /** RegularExpression Id. */
  int OP_MUL = 20;
  /** RegularExpression Id. */
  int OP_DIV = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<VAR>",
    "<NUM>",
    "\"||\"",
    "\"&&\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"=\"",
    "\"!=\"",
    "\"@inf\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\n\"",
  };

}
