/* Generated By:JavaCC: Do not edit this line. InvariantTreeConstants.java Version 5.0 */
public interface InvariantTreeConstants
{
  public int JJTINV_EXP = 0;
  public int JJTOREXPR = 1;
  public int JJTANDEXPR = 2;
  public int JJTATOMINV = 3;
  public int JJTRANGE = 4;
  public int JJTSET = 5;
  public int JJTARITM = 6;
  public int JJTSUMEXPR = 7;
  public int JJTMULTEXPR = 8;
  public int JJTATOM = 9;


  public String[] jjtNodeName = {
    "Inv_exp",
    "OrExpr",
    "AndExpr",
    "atomInv",
    "Range",
    "Set",
    "Aritm",
    "SumExpr",
    "multExpr",
    "atom",
  };
}
/* JavaCC - OriginalChecksum=25b1b82220085b054ddb2399e953526f (do not edit this line) */
